prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/mobile_main_menu.sql
@@application/shared_components/navigation/lists/application_navigation.sql
@@application/shared_components/navigation/lists/customers.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/preferences.sql
@@application/shared_components/navigation/lists/customer_actions.sql
@@application/shared_components/navigation/lists/data_load_process_train_customers.sql
@@application/shared_components/navigation/lists/administrative_code_tables.sql
@@application/shared_components/navigation/lists/data_load_process_train_contacts.sql
@@application/shared_components/navigation/lists/additional_administration.sql
@@application/shared_components/navigation/lists/mobile_menu.sql
@@application/shared_components/navigation/lists/user_activity_reports.sql
@@application/shared_components/navigation/lists/load_customers_train.sql
@@application/shared_components/navigation/lists/administration.sql
@@application/shared_components/navigation/lists/reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/welome_actions.sql
@@application/shared_components/navigation/lists/data_load_process_train_customers_002.sql
@@application/shared_components/navigation/lists/data_load_process_train_customers_003.sql
@@application/shared_components/navigation/lists/data_load_process_train_customers_004.sql
@@application/shared_components/navigation/lists/activity_actions.sql
@@application/shared_components/navigation/lists/administrative_logs.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/copy_of_administration_rights.sql
@@application/shared_components/security/authorizations/edit_competitors.sql
@@application/shared_components/security/authorizations/view_competitors.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/application_sentry.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/timezone.sql
@@application/shared_components/logic/application_processes/set_globals.sql
@@application/shared_components/logic/application_processes/get_image.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/active_msg.sql
@@application/shared_components/logic/application_items/activities.sql
@@application/shared_components/logic/application_items/application_title.sql
@@application/shared_components/logic/application_items/category_help.sql
@@application/shared_components/logic/application_items/cnt_01.sql
@@application/shared_components/logic/application_items/cnt_02.sql
@@application/shared_components/logic/application_items/cnt_03.sql
@@application/shared_components/logic/application_items/cnt_04.sql
@@application/shared_components/logic/application_items/cnt_05.sql
@@application/shared_components/logic/application_items/cnt_06.sql
@@application/shared_components/logic/application_items/cnt_07.sql
@@application/shared_components/logic/application_items/cnt_08.sql
@@application/shared_components/logic/application_items/cnt_09.sql
@@application/shared_components/logic/application_items/cnt_10.sql
@@application/shared_components/logic/application_items/contacts.sql
@@application/shared_components/logic/application_items/contact_types_help.sql
@@application/shared_components/logic/application_items/create_msg.sql
@@application/shared_components/logic/application_items/customer.sql
@@application/shared_components/logic/application_items/customers.sql
@@application/shared_components/logic/application_items/customer_status_help.sql
@@application/shared_components/logic/application_items/customer_type_help.sql
@@application/shared_components/logic/application_items/customer_use_case_help.sql
@@application/shared_components/logic/application_items/get_id.sql
@@application/shared_components/logic/application_items/inactive_msg.sql
@@application/shared_components/logic/application_items/last_view.sql
@@application/shared_components/logic/application_items/products.sql
@@application/shared_components/logic/application_items/return_url.sql
@@application/shared_components/logic/application_items/tz.sql
@@application/shared_components/logic/application_items/unlink_confirm_msg.sql
@@application/shared_components/logic/application_computations/application_title.sql
@@application/shared_components/logic/application_computations/customer_type_help.sql
@@application/shared_components/logic/application_computations/customer_use_case_help.sql
@@application/shared_components/logic/application_computations/create_msg.sql
@@application/shared_components/logic/application_computations/unlink_confirm_msg.sql
@@application/shared_components/logic/application_computations/active_msg.sql
@@application/shared_components/logic/application_computations/inactive_msg.sql
@@application/shared_components/logic/application_computations/category_help.sql
@@application/shared_components/logic/application_computations/customer_status_help.sql
@@application/shared_components/logic/application_computations/contact_types_help.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_control_scope.sql
@@application/shared_components/user_interface/lovs/access_control_scope1.sql
@@application/shared_components/user_interface/lovs/access_levels.sql
@@application/shared_components/user_interface/lovs/active_categories_p2.sql
@@application/shared_components/user_interface/lovs/active_contact_types_p20.sql
@@application/shared_components/user_interface/lovs/active_statuses_p2.sql
@@application/shared_components/user_interface/lovs/activities.sql
@@application/shared_components/user_interface/lovs/activity_types.sql
@@application/shared_components/user_interface/lovs/available_products.sql
@@application/shared_components/user_interface/lovs/cat.sql
@@application/shared_components/user_interface/lovs/contact_types.sql
@@application/shared_components/user_interface/lovs/contacts.sql
@@application/shared_components/user_interface/lovs/countries.sql
@@application/shared_components/user_interface/lovs/countries_p2.sql
@@application/shared_components/user_interface/lovs/countries_p59.sql
@@application/shared_components/user_interface/lovs/customers.sql
@@application/shared_components/user_interface/lovs/data_load_charset.sql
@@application/shared_components/user_interface/lovs/data_load_option.sql
@@application/shared_components/user_interface/lovs/data_load_tab_status.sql
@@application/shared_components/user_interface/lovs/date_format_option.sql
@@application/shared_components/user_interface/lovs/eba_cust_tables.sql
@@application/shared_components/user_interface/lovs/feedback_statuses.sql
@@application/shared_components/user_interface/lovs/feedback_types.sql
@@application/shared_components/user_interface/lovs/first_row_option.sql
@@application/shared_components/user_interface/lovs/geography.sql
@@application/shared_components/user_interface/lovs/homepage_display_as.sql
@@application/shared_components/user_interface/lovs/is_active.sql
@@application/shared_components/user_interface/lovs/issue_statuses.sql
@@application/shared_components/user_interface/lovs/issue_types.sql
@@application/shared_components/user_interface/lovs/label_templates.sql
@@application/shared_components/user_interface/lovs/link_types.sql
@@application/shared_components/user_interface/lovs/logo_sizes.sql
@@application/shared_components/user_interface/lovs/lov_dataload_customers.sql
@@application/shared_components/user_interface/lovs/marquee.sql
@@application/shared_components/user_interface/lovs/max_rows.sql
@@application/shared_components/user_interface/lovs/notification_type.sql
@@application/shared_components/user_interface/lovs/p2_industry_id_lookup.sql
@@application/shared_components/user_interface/lovs/p50_product.sql
@@application/shared_components/user_interface/lovs/p68_product.sql
@@application/shared_components/user_interface/lovs/p68_prod_use_external_contact.sql
@@application/shared_components/user_interface/lovs/product_families.sql
@@application/shared_components/user_interface/lovs/product_statuses.sql
@@application/shared_components/user_interface/lovs/products.sql
@@application/shared_components/user_interface/lovs/referencable.sql
@@application/shared_components/user_interface/lovs/reference_phase.sql
@@application/shared_components/user_interface/lovs/reference_types.sql
@@application/shared_components/user_interface/lovs/rows.sql
@@application/shared_components/user_interface/lovs/report_row_per_page.sql
@@application/shared_components/user_interface/lovs/show_customer_views_checkbox.sql
@@application/shared_components/user_interface/lovs/status.sql
@@application/shared_components/user_interface/lovs/statuses.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/type.sql
@@application/shared_components/user_interface/lovs/upload_action.sql
@@application/shared_components/user_interface/lovs/username_format.sql
@@application/shared_components/user_interface/lovs/use_case.sql
@@application/shared_components/user_interface/lovs/y_or_n.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb1.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/timezone.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/reports/report_layouts/customer_report.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_status.sql
@@application/shared_components/plugins/region_type/com_oracle_auth_administration.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_minicalendar.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_validator.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_completeness.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_warning.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_html5_bar_chart.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_tag_cloud.sql
@@application/shared_components/legacy_data_loads/eba_cust_contacts.sql
@@application/shared_components/legacy_data_loads/eba_cust_customers.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00040.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00070.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00108.sql
@@application/pages/page_00109.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00112.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00119.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00125.sql
@@application/pages/page_00126.sql
@@application/pages/page_00127.sql
@@application/pages/page_00128.sql
@@application/pages/page_00129.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00133.sql
@@application/pages/page_00134.sql
@@application/pages/page_00145.sql
@@application/pages/page_00149.sql
@@application/pages/page_00150.sql
@@application/pages/page_00175.sql
@@application/pages/page_00192.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/upgrade_framework_package.sql
@@application/deployment/install/install_set_plscope_settings.sql
@@application/deployment/install/upgrade_add_parent_customer_id.sql
@@application/deployment/install/install_error_log.sql
@@application/deployment/install/upgrade_framework_body.sql
@@application/deployment/install/install_framework_spec.sql
@@application/deployment/install/upgrade_allow_null_preference_values.sql
@@application/deployment/install/install_create_sequence.sql
@@application/deployment/install/upgrade_username_format_preference.sql
@@application/deployment/install/install_timezone.sql
@@application/deployment/install/upgrade_implementation_partners_competitors.sql
@@application/deployment/install/install_eba_cust_spec.sql
@@application/deployment/install/upgrade_activities.sql
@@application/deployment/install/install_eba_cust_sample_data_spec.sql
@@application/deployment/install/install_geographies.sql
@@application/deployment/install/upgrade_industry_view.sql
@@application/deployment/install/upgrade_add_contact_columns.sql
@@application/deployment/install/install_countries.sql
@@application/deployment/install/upgrade_product_families.sql
@@application/deployment/install/history.sql
@@application/deployment/install/upgrade_remove_help_table.sql
@@application/deployment/install/install_access_levels_and_users.sql
@@application/deployment/install/upgrade_history_triggers.sql
@@application/deployment/install/install_lookup.sql
@@application/deployment/install/upgrade_click_counting_table.sql
@@application/deployment/install/install_preferences.sql
@@application/deployment/install/upgrade_content_validation_table.sql
@@application/deployment/install/install_industries.sql
@@application/deployment/install/install_categories.sql
@@application/deployment/install/upgrade_eba_cust_customers_trigger.sql
@@application/deployment/install/install_customer_statuses.sql
@@application/deployment/install/upgrade_reference_types.sql
@@application/deployment/install/install_customer_types.sql
@@application/deployment/install/upgrade_add_phase_table.sql
@@application/deployment/install/install_customer_use_cases.sql
@@application/deployment/install/upgrade_add_reference_phase_id.sql
@@application/deployment/install/install_product_families.sql
@@application/deployment/install/upgrade_sales_channel.sql
@@application/deployment/install/upgrade_add_sales_channel.sql
@@application/deployment/install/install_products.sql
@@application/deployment/install/install_eba_cust_sales_channel.sql
@@application/deployment/install/upgrade_recruitment_owner.sql
@@application/deployment/install/upgrade_new_product_uses_columns.sql
@@application/deployment/install/install_customers.sql
@@application/deployment/install/upgrade_drop_product_customer_constraint_in_product_uses.sql
@@application/deployment/install/install_contact_types.sql
@@application/deployment/install/install_contacts.sql
@@application/deployment/install/upgrade_drop_index_eba_cust_product_uses_uk.sql
@@application/deployment/install/upgrade_add_eba_cust_prod_uses_contact_fk.sql
@@application/deployment/install/install_product_uses.sql
@@application/deployment/install/upgrade_product_statuses.sql
@@application/deployment/install/install_product_statuses.sql
@@application/deployment/install/install_reference_types.sql
@@application/deployment/install/upgrade_add_logo_columns_to_customers_table.sql
@@application/deployment/install/install_customer_files.sql
@@application/deployment/install/upgrade_strategic_customer_program_yn.sql
@@application/deployment/install/upgrade_country_id_in_customers_table.sql
@@application/deployment/install/install_customer_links.sql
@@application/deployment/install/install_customer_view_log.sql
@@application/deployment/install/upgrade_eba_cust_type.sql
@@application/deployment/install/install_customer_admins.sql
@@application/deployment/install/upgrade_type_id_into_customers_table.sql
@@application/deployment/install/upgrade_eba_cust_use_case.sql
@@application/deployment/install/install_tags.sql
@@application/deployment/install/install_issues.sql
@@application/deployment/install/upgrade_use_case_id_into_customers_table.sql
@@application/deployment/install/install_implementation_partners.sql
@@application/deployment/install/upgrade_add_party_attributes.sql
@@application/deployment/install/install_competitors.sql
@@application/deployment/install/upgrade_region_id_in_countries.sql
@@application/deployment/install/install_activities.sql
@@application/deployment/install/upgrade_feedback_types_ddl.sql
@@application/deployment/install/upgrade_feedback_types_data.sql
@@application/deployment/install/install_create_triggers.sql
@@application/deployment/install/upgrade_feedback_ddl.sql
@@application/deployment/install/eba_cust_customers_trigger.sql
@@application/deployment/install/upgrade_email_log_ddl.sql
@@application/deployment/install/install_framework_body.sql
@@application/deployment/install/install_load_base_data.sql
@@application/deployment/install/upgrade_eba_cust_email_package_spec.sql
@@application/deployment/install/upgrade_eba_cust_email_package_body.sql
@@application/deployment/install/install_load_acl_data.sql
@@application/deployment/install/upgrade_add_total_contract_value_discount_level_to_customers_table.sql
@@application/deployment/install/install_create_eba_cust_acl_features.sql
@@application/deployment/install/upgrade_create_eba_cust_acl_features.sql
@@application/deployment/install/install_eba_cust_body.sql
@@application/deployment/install/upgrade_upgrade_eba_cust_spec_and_body.sql
@@application/deployment/install/install_notifications.sql
@@application/deployment/install/install_notes.sql
@@application/deployment/install/upgrade_populate_eba_cust_acl_features.sql
@@application/deployment/install/upgrade_upgrade_eba_cust_sample_data.sql
@@application/deployment/install/install_eba_cust_sample_data_body.sql
@@application/deployment/install/upgrade_issue_statuses.sql
@@application/deployment/install/install_add_ddl_comments.sql
@@application/deployment/install/upgrade_issues.sql
@@application/deployment/install/install_view.sql
@@application/deployment/install/install_click_counting_table.sql
@@application/deployment/install/upgrade_customer_after_delete_trigger.sql
@@application/deployment/install/install_content_validation_table.sql
@@application/deployment/install/upgrade_timestamp_fix_bugid_31352674.sql
@@application/deployment/install/upgrade_update_countries_region_ids.sql
@@application/deployment/install/install_phase.sql
@@application/deployment/install/install_feedback_tables_data_and_triggers.sql
@@application/deployment/install/upgrade_set_first_run_preference.sql
@@application/deployment/install/install_email_log_ddl.sql
@@application/deployment/install/install_eba_cust_email_package_spec.sql
@@application/deployment/install/install_eba_cust_email_package_body.sql
@@application/deployment/install/install_set_first_run_preference.sql
@@application/deployment/install/install_populate_eba_cust_acl_features.sql
@@application/deployment/install/install_customer_after_delete_trigger.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
