CREATE TABLE APXVERSION$APP
(
  APP_ID      NUMBER,
  APP_REPO    VARCHAR2(100 BYTE) COLLATE USING_NLS_COMP,
  APP_BRANCH  VARCHAR2(100 BYTE) COLLATE USING_NLS_COMP,
  AUDIT_DATE  DATE,
  DEVELOPER   VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP
)
DEFAULT COLLATION USING_NLS_COMP
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
