SET DEFINE OFF;

-- USER SQL
CREATE USER "APEX_VERSION_USER" IDENTIFIED BY "*************";

-- ROLES
GRANT "CONNECT" TO "APEX_VERSION_USER";

--  PRIVILEGES
GRANT SELECT ON "APEX_XXXXXX"."WWV_FLOW_BUILDER_AUDIT_TRAIL" TO "APEX_VERSION_USER";

GRANT SELECT ON "APEX_XXXXXX"."WWV_FLOW_AUTHORIZED" TO "APEX_VERSION_USER";

GRANT SELECT, INSERT ON "APEX_XXXXXX"."WWV_FLOW_LOCK_PAGE" TO "APEX_VERSION_USER";

GRANT SELECT ON "APEX_XXXXXX"."WWV_FLOW_LOCK_PAGE_LOG" TO "APEX_VERSION_USER";

GRANT APEX_ADMINISTRATOR_READ_ROLE to TO "APEX_VERSION_USER";